SELECT D.NUME AS DISCIPLINA, F.NUME AS FACULTATEA, SS.NUME AS SPECIALITATEA, G.NUME AS GRUPA, L.NUME AS EXAMINATOR, EX.DATA_EXAMINARII

	FROM SPECIALITATE SS INNER JOIN GRUPA G ON G.SPECIALITATE_ID = SS.SPECIALITATE_ID
						 INNER JOIN EXAMINARE EX ON EX.SPECIALITATEA_ID = SS.SPECIALITATE_ID
						 INNER JOIN DISCIPLINA D ON D.DISCIPLINA_ID = EX.DISCIPLINA_ID
						 INNER JOIN LECTOR L ON L.LECTOR_ID = EX.LECTOR_ID
						 INNER JOIN FACULTATE F ON F.FACULTATE_ID = SS.FACULTATE_ID
ORDER BY D.NUME ASC