UPDATE LECTOR SET LOGIN = 'MOSNEAGA841', PASSWORD = 'MVSTEP408' WHERE LECTOR_ID = 8;
UPDATE LECTOR SET LOGIN = 'CALDARE392',  PASSWORD = 'CISTEP318' WHERE LECTOR_ID = 9;
UPDATE LECTOR SET LOGIN = 'CIUBOTA485',  PASSWORD = 'CVSTEP581' WHERE LECTOR_ID = 10;
UPDATE LECTOR SET LOGIN = 'MANALUNGA679',PASSWORD = 'MPSTEP741' WHERE LECTOR_ID = 11;
UPDATE LECTOR SET LOGIN = 'NEGRU832',    PASSWORD = 'NASTEP630' WHERE LECTOR_ID = 12;

SELECT * FROM LECTOR