

SELECT S.NUME, S.PRENUME, IIF (S.GEN = 1, 'MASCULIN', 'FEMININ') AS GEN, S.IDNP, G.NUME,
	(SELECT CONVERT(DECIMAL(7,2), AVG(N.NOTA)) FROM NOTA N INNER JOIN STUDENT S ON S.STUDENT_ID = N.STUDENT_ID
														   INNER JOIN GRUPA GG ON GG.GRUPA_ID = S.GRUPA_ID
			WHERE G.GRUPA_ID = GG.GRUPA_ID) AS MEDIA_GRUPA,
	(SELECT CONVERT(DECIMAL(7,2), AVG(N.NOTA)) FROM NOTA N INNER JOIN STUDENT SS ON SS.STUDENT_ID = N.STUDENT_ID
			WHERE SS.STUDENT_ID = S.STUDENT_ID) AS MEDIA_STUD
	FROM STUDENT S INNER JOIN NOTA N ON N.STUDENT_ID = S.STUDENT_ID
				   INNER JOIN GRUPA G ON G.GRUPA_ID = S.GRUPA_ID
				   INNER JOIN EXAMINARE EX ON EX.EXAMINARE_ID = N.EXAMINARE_ID
				   INNER JOIN DISCIPLINA D ON D.DISCIPLINA_ID = EX.DISCIPLINA_ID
WHERE G.NUME = :GROUP
GROUP BY S.NUME, S.PRENUME, IIF (S.GEN = 1, 'MASCULIN', 'FEMININ'), S.IDNP, G.NUME, G.GRUPA_ID, S.STUDENT_ID
ORDER BY S.NUME ASC